[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[window]
opacity = 0.9
decorations = "None"

# [window.dimensions]
# columns = 209
# lines = 41

[window.padding]
x = 5
y = 5

[general]
import = ["/home/marcusvrp/.config/alacritty/themes/mocha.toml"]
